name: Flowable SBOM Build

on:
  release:
    types:
      - created

jobs:
  build_java_and_docker:
    name: Linux (JDK 13)
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: adito/flowable
    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 10
    - uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Install
      run: ./mvnw clean install -V -B --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pdistro
    - name: Build an image from Dockerfile
      run: cd docker/all-in-one && ./build.sh ${{ github.ref_name }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image to Docker Hub
      run: docker push $IMAGE_NAME:${{ github.ref_name }}

    - name: Create SBOM for Jars
      run: |
        mvn -T 1C org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom

    #- name: Build an image from Dockerfile
    #  run: docker build -t docker.io/adito/flowable:${{ github.ref_name }} .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.35.0
      with:
        image-ref: '${{ env.IMAGE_NAME }}:${{ github.ref_name }}'
        format: 'cyclonedx'
        output: 'target/trivy.json'

    - name: Merge + validate (CycloneDX CLI via Docker)
      run: |
        docker run --rm \
          -v "${GITHUB_WORKSPACE}:/work" \
          -w /work \
          cyclonedx/cyclonedx-cli \
          merge --input-files target/bom.json target/trivy.json --output-file target/combined-sbom.json

    - name: Convert combined SBOM to CycloneDX 1.6
      run: |
        docker run --rm \
          -v "${GITHUB_WORKSPACE}:/work" \
          -w /work \
          cyclonedx/cyclonedx-cli \
          convert --input-file target/combined-sbom.json --output-file target/combined-sbom-1.6.json --output-version v1_6 --output-format json

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0

    - name: Attach SBOM to image in Docker Hub
      run: cosign attach sbom --sbom target/combined-sbom-1.6.json --type cyclonedx $IMAGE_NAME:${{ github.ref_name }}

    - name: Upload SBOM to Dependency-Track
      uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5
      with:
        serverHostname: ${{ secrets.DEPENDENCYTRACK_HOSTNAME }}
        apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
        projectName: ${{ github.event.repository.name }}
        projectVersion: ${{ github.ref_name }}
        projectTags: 'flowable-modeler,${{ github.event.repository.name }}'
        bomFilename: "target/combined-sbom-1.6.json"
        autoCreate: true
